### PR TITLE
#3: CLI improvement

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
Use commons-cli for reading configuration from command line.

### CODE REVIEW

**Comment by raihan26** [comment]
I cloned this project and I imported in my eclipse but somehow it is not able to find this class "ImmutableConfiguration" in "ZkCopy" class.  The error I see is this - "ImmutableConfiguration cannot be resolved". What library this class is part of? Or Am I missing something?

**Comment by kshchepanovskyi** [comment]
@raihan26 
Run `mvn clean install` - this class is generated as a part of build process, check https://immutables.github.io/ for more information.

**Comment by raihan26** [comment]
Ok that makes sense. If I am using everything from command prompt, it looks fine but in the eclipse how do I remove that error (I already ran clean install through eclipse)? I am able to run in eclipse though without any issues but everytime it complains that error is there in project but it does work fine without any issues.

**Comment by kshchepanovskyi** [comment]
Sorry, I'm not using Eclipse (switched to IntelliJ IDEA long time ago), so the only thing I can recommend - google for "java immutables eclipse" or something like this, most likely somebody had similar issue.

**Comment by kshchepanovskyi** [comment]
Maybe this will help: https://immutables.github.io/apt.html

**Comment by raihan26** [comment]
Yeah that's what I am looking at. Thanks for the help.

**Pull request merged**
